controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
ajouter_offre:
    path: /ajouter-offre
    methods: POST
    controller: App\Controller\AuctionController::updateOffer